services:
  pg15:
    image: postgres:15
    container_name: pg15
    restart: always
    volumes:
      - pg15_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    networks:
      - social-adonis-network

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379
    networks:
      - social-adonis-network

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    tty: true
    restart: on-failure
    volumes:
      - mailhog_volume:/data
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # UI
    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 1025
    networks:
      - social-adonis-network

  adonis_app:
    container_name: adonis_app
    build:
      context: .
      target: deps
    ports:
      - 3000:3000
      - 24678:24678
    env_file:
      - .env
    environment:
      - DB_HOST=pg15
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - social-adonis-network
    command: yarn dev

volumes:
  pg15_volume:
  redis_volume:
  mailhog_volume:

networks:
  social-adonis-network:
