#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

yarn format ||
(
    echo '😤🏀👋😤 Prettier Check Failed. Run yarn format, add changes and try to commit again.';
    false;
)

yarn lint ||
(
    echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above and try to commit again.'
    false; 
)

yarn typecheck ||
(
    echo '😤🏀👋😤 TS Check Failed. Make the required changes listed above and try to commit again.'
    false; 
)
